spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}

  application:
    name:
      payment-system

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  messages:
    basename: message
    fallback-to-system-locale: false
    use-code-as-default-message: false
    encoding: UTF-8
  web:
    locale: az
    locale-resolver: fixed


  liquibase:
    default-schema: public
    liquibase-schema: public
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true


bank:
  fraud:
    max-account-creations: 3
  card:
    min-balance: 10
    min-balance-currency: AZN
    number:
      prefix: "9988"
      total-length: 16
  account:
    min-balance: 5
    min-balance-currency: USD
    number:
      prefix: "2211"
      total-length: 18
  transaction:
    suspicious-threshold: 100
    suspicious-currency: AZN

scheduler:
  payment:
    cron: "0 5 0 * * *"
  card:
    cron: "0 0 0 * * *"
  currentAccount:
    cron: "0 1 0 * * *"



